apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnap-demo-backend-v2
  namespace: cnap-mp-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cnap-demo-backend
      version: v2
      env: dev
  template:
    metadata:
      labels:
        app: cnap-demo-backend
        version: v2
        env: dev
    spec:
      containers:
      - image: kvn0218/kuma-demo-be:latest
        resources:
         requests:
          cpu: 15m
          memory: 105M
         limits:
          cpu: 15m
          memory: 105M
        name: kuma-be
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: TOTAL_OFFER
          value: "2"
        - name: REDIS_HOST
          value: redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001